### ISSUE TITLE
CrystalDock disappears during drop to desktop

### ISSUE THREAD

**Issue by 2handband** [dangvd/crystal-dock#59] opened 2024-09-27 23:25 UTC
This behavior takes place when I show desktop using the hotkey, and also when I do so using a screen corner action. I tested it with both always visible and auto-hide; got same result.

Expected behavior: Crystal-Dock continues to function during show desktop/ drop to desktop actions.

Observed behavior: Crystal-Dock disappears/ceases to function during show desktop/ drop to desktop actions. Function returns when the application windows are brought back up.

**Comment by dangvd** [comment] 2024-09-28 13:16
Hi,

This doesn't seem straightforward to fix, but I'll try to look into it.

**Comment by dangvd** [comment] 2024-09-28 15:41
Update: On my system, this is the case with KDE Plasma 6 panels as well, so it seems to be expected behaviour.

**Comment by 2handband** [comment] 2024-09-28 16:32
@dangvd: so your auto-hidden plasma panels also fail to activate during drop to desktop? I  just tried it on my system, and that isn't the case here. The auto-hidden panel functioned as usual.

**Comment by dangvd** [comment] 2024-09-28 23:31
Ah sorry my screen corner action might be a bit different from yours.
Yeah if you click Show Desktop from a KDE Plasma panel or use a Show Desktop hotkey, Crystal Dock will not be shown.

The current work around is if you click Show Desktop from within Crystal Dock i.e. click on the Pager (Desktop 1 / 2 /etc) then it should show Crystal Dock.

**Comment by dangvd** [comment] 2024-10-18 19:44
On my Kubuntu 24.10 running KDE Plasma 6.1.5, if I click on Show Desktop on a Plasma panel, Crystal Dock does show now.

@2handband: you're still having this bug? What's your KDE Plasma version?

**Comment by EliteAMDGamer** [comment] 2024-10-26 19:36
It also seems to quit crystal dock when the display is shut off. I would guess Its when the GPU changes state in wayland.
 I'm not sure if i can but I may try to make a script to reopen it when the display turns on. 

```
Operating System: Garuda Linux 
KDE Plasma Version: 6.2.2
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.11.5-2-cachyos (64-bit)
Graphics Platform: Wayland
Graphics Processor: AMD Radeon RX 7900 GRE
```

**Comment by dangvd** [comment] 2024-10-26 20:27
@EliteAMDGamer you mean when you turn off the monitor or when it sleeps e.g. energy saving?

**Comment by EliteAMDGamer** [comment] 2024-10-26 20:31
It happens in my case when either I manually shut off the monitor when I walk away from the system.  Or when the display automatically shuts off after four hours of inactivity. 

I don't use sleep or anything currently because they don't really function to well. But the dock will appear with autostart on boot or sddm login. 

I have not tested it with plasma's lock screen, but I don't think it would open then either.

**Comment by dangvd** [comment] 2024-10-30 15:29
@EliteAMDGamer I've created a separate bug for your issue #98 as this one is not for that.

**Comment by dangvd** [comment] 2024-10-30 21:42
Closing this bug as Not Reproducible.

**Closed by dangvd** 2024-10-30 21:42 UTC
Labels: not reproducible
