### ISSUE TITLE
KDE Plasma 6, Display Scale > 100%: Icons look broken

### ISSUE THREAD

**Issue by asjur** [dangvd/crystal-dock#32] opened 2024-08-02 15:12 UTC
I've attached a photo that shows the issue.

Basically it seems like crystal-dock does not scale icons correctly (the workspace switcher also doesn't look right).
This is under Arch built from source.

![image](https://github.com/user-attachments/assets/baf29401-2910-48fa-bf78-79425c5d16c3)

**Comment by asjur** [comment] 2024-08-03 01:35
I also tried the same theme you recommend in the Readme with the exact same result.

**Comment by dangvd** [comment] 2024-08-03 18:38
Umm I'm not sure why this is happening on your end, as I can't reproduce it.
The icon scaling code has been there for years and I have never seen this.

What's your KDE Plasma version btw?

**Comment by asjur** [comment] 2024-08-03 22:40
![image](https://github.com/user-attachments/assets/5b7aa0e9-5152-4bb9-b6fc-208c3da90966)

My display is scaled at 200% however.

**Comment by dangvd** [comment] 2024-08-03 22:51
Thanks I'll update mine to the same version and check it.

**Comment by dangvd** [comment] 2024-08-07 23:41
Hi,
I've updated my KDE Plasma to 6.1.3 (OpenSUSE Tumbleweed) but could not reproduce your issue.

**Comment by asjur** [comment] 2024-08-08 09:14
> Hi, I've updated my KDE Plasma to 6.1.3 (OpenSUSE Tumbleweed) but could not reproduce your issue.

Did you try scaling your display to 200%?

**Comment by dangvd** [comment] 2024-08-08 12:53
Yes I can reproduce it now when setting Display Scale to a value > 100%.
Not sure how to fix yet though.

**Comment by dangvd** [comment] 2024-08-20 15:33
Fixed in the main branch. Will release in version 2.3 soon when I'm done with a few other changes.

**Comment by dangvd** [comment] 2024-09-14 12:10
Fixed in v2.3

**Closed by dangvd** 2024-09-14 12:10 UTC
Labels: bug
