### ISSUE TITLE
No Click Response When Quickly Accessing the Dock

### ISSUE THREAD

**Issue by bluee111** [dangvd/crystal-dock#61] opened 2024-09-28 21:07 UTC
Excellent Dock, my friend, we really needed it :D. I just want to inform you that when I go to the dock quickly, the click doesn't respond. To be clearer, I will leave a video here for you to see. Thank you very much for developing this.
https://1drv.ms/v/s!Apmd2Q-DQX0Egmo3sH7uHwTNnkt1?e=vvd5w6

**Comment by dangvd** [comment] 2024-09-29 13:00
Thanks for your comment!

And sorry about the bug. Does it also happen when you go to the dock not too quickly?
I couldn't reproduce the bug yet btw.

**Comment by dangvd** [comment] 2024-10-30 21:42
Closing as Not Reproducible.

**Closed by dangvd** 2024-10-30 21:42 UTC
Labels: not reproducible
