### ISSUE TITLE
Can't pin icons app

### ISSUE THREAD

**Issue by waal** [dangvd/crystal-dock#45] opened 2024-09-03 00:04 UTC
I tried to apply the solutions in Issue #13 and Issue #9 without results.

I can't pin "Add/Remove Software" for instance and no icon is shown. Same goes for some apps like Reaper.  It seems to be random. And I see no difference looking into KDE menu editor. Editing the program path changes nothing.

I use Manjaro KDE with plasma 6.

![Screenshot_20240903_010332](https://github.com/user-attachments/assets/90d62fad-79c6-40ba-98e5-cd56f32804b4)

**Comment by waal** [comment] 2024-09-03 00:44
My KDE menu editor has no control over Crystal Dock's Application Menu but works fine with any other default widget like "application launcher" inside other panels.

![Screenshot_20240903_012012](https://github.com/user-attachments/assets/6a801f7a-eaef-4003-81bd-d263ea3530f1)

**Comment by dangvd** [comment] 2024-09-05 23:00
Hi,

Your first post seems to be a duplicate of this bug #21 : I'm looking at it

Your second post: KDE menu editor should work with Crystal Dock's application list, because Crystal Dock reads from the standard location using standard attributes. Note that an entry won't be visible if for example, its desktop file specifies (using standard attributes) that it is noDisplay, or Hidden, or the type is not Application, or not show in the current desktop environment, or only show in another desktop environment.

**Comment by waal** [comment] 2024-09-08 15:47
Thank you for the explanation. I will wait for issue #21 to be solved then.

**Comment by dangvd** [comment] 2024-09-15 14:47
Can you list some apps that you can't pin? I can't seem to reproduce it anymore after a recent system update. Maybe the update fixed it? (for example, if QIcon::fromTheme now search for more backup locations)

Also let me know your system info: Qt and KDE / Plasma version.

Thanks,

**Comment by dangvd** [comment] 2024-09-15 16:40
Feel free to respond in the other bug #21

**Closed by dangvd** 2024-09-15 16:40 UTC
