### ISSUE TITLE
Some tasks do not appear on all screens when "showing tasks from all screen" is set

### ISSUE THREAD

**Issue by dwconsulting** [dangvd/crystal-dock#74] opened 2024-10-07 13:05 UTC
Built from the latest main source, I pinned a couple of applications. On computer start-up, without launching either of the two, they only show up on one dock:
Dock 1
![image](https://github.com/user-attachments/assets/95bcb130-3235-4a95-8266-99b99bb65acc)

Dock 2
![image](https://github.com/user-attachments/assets/4ca5e117-06f5-49f7-9259-b0e4295da07e)

In addition, you can see that Writer shows up on dock 2 but NOT on dock 1, and that was launched after the docks loaded.

**Comment by dwconsulting** [comment] 2024-10-07 13:07
Update: 
If I go into "Task Manager Settings", check and uncheck "Current Screen Only" (at launch it is unchecked) then click "Apply", "OK" the running applications show up on both docks.

**Comment by dangvd** [comment] 2024-10-07 21:30
Hi,
For the first one: it's intended behaviour, because they are 2 separate docks. When you pin an application on one dock, it only affects that one.
Second one seems like a bug -- I will verify it and create an issue.

**Comment by dangvd** [comment] 2024-10-25 18:42
Second one is a bug -- I'm working on a fix.

**Comment by dangvd** [comment] 2024-10-25 19:05
Fixed in the main tree.

**Comment by dangvd** [comment] 2024-10-26 00:05
Fix released in v2.7

**Closed by dangvd** 2024-10-26 00:05 UTC
Labels: bug
