### ISSUE TITLE
Lock screen functions but no password gets you back in 

### ISSUE THREAD

**Issue by Detritus78** [dangvd/crystal-dock#10] opened 2023-09-07 15:28 UTC
Lock screen locks the screen however, no password gets you back in. You  have to select switch user to log back in. 

Operating System: MX Linux 23
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.4.11-1-liquorix-amd64 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6600 XT
Manufacturer: NZXT, Inc
Product Name: B550 UD AC

**Comment by dangvd** [comment] 2023-09-07 22:15
I'm running Gnome at the moment but I will try to have a KDE Plasma desktop to test it.

**Comment by dangvd** [comment] 2023-11-11 19:31
Tested on OpenSuSe Tumbleweed with KDE Plasma 5.27.9 but could not reproduce this issue. Closing.

**Closed by dangvd** 2023-11-11 19:31 UTC
